import { User, Medication, Prescription, Order } from "./types";

export const MOCK_CURRENT_USER: User = {
  id: "user-paciente-1",
  nome_completo: "Maria de Lourdes da Silva",
  email: "maria.lourdes@email.com",
  cpf: "123.456.789-00",
  cartao_sus: "748 3920 1823 0001",
  telefone: "(11) 98765-4321",
  role: "PACIENTE",
  endereco_rua: "Rua das Flores",
  endereco_numero: "250",
  endereco_bairro: "Jardim das Palmeiras",
  endereco_cidade: "São Paulo",
  endereco_uf: "SP",
  endereco_cep: "04567-000",
};

export const MOCK_MEDICATIONS: Medication[] = [
  {
    id: "med-1",
    codigo_catmat: "BR0289110",
    nome_comercial: "Losartana Potássica",
    principio_ativo: "Losartana Potássica",
    dosagem: "50mg",
    forma_farmaceutica: "Comprimido",
    categoria: "BASICO",
    exige_receita: true,
    temperatura_controlada: false,
    estoque_disponivel: 1420,
  },
  {
    id: "med-2",
    codigo_catmat: "BR0291432",
    nome_comercial: "Metformina (Glifage)",
    principio_ativo: "Cloridrato de Metformina",
    dosagem: "850mg",
    forma_farmaceutica: "Comprimido",
    categoria: "BASICO",
    exige_receita: true,
    temperatura_controlada: false,
    estoque_disponivel: 980,
  },
  {
    id: "med-3",
    codigo_catmat: "BR0314590",
    nome_comercial: "Insulina NPH Humana",
    principio_ativo: "Insulina Humana NPH",
    dosagem: "100 UI/ml - Frasco 10ml",
    forma_farmaceutica: "Suspensão Injetável",
    categoria: "BASICO",
    exige_receita: true,
    temperatura_controlada: true,
    estoque_disponivel: 150,
  },
  {
    id: "med-4",
    codigo_catmat: "BR0189004",
    nome_comercial: "Adalimumabe (Humira)",
    principio_ativo: "Adalimumabe",
    dosagem: "40mg/0,8ml",
    forma_farmaceutica: "Solução Injetável (Seringa)",
    categoria: "ALTO_CUSTO",
    exige_receita: true,
    temperatura_controlada: true,
    estoque_disponivel: 34,
  },
  {
    id: "med-5",
    codigo_catmat: "BR0345129",
    nome_comercial: "Sinvastatina",
    principio_ativo: "Sinvastatina",
    dosagem: "20mg",
    forma_farmaceutica: "Comprimido",
    categoria: "BASICO",
    exige_receita: true,
    temperatura_controlada: false,
    estoque_disponivel: 610,
  },
  {
    id: "med-6",
    codigo_catmat: "BR0412890",
    nome_comercial: "Rivotril",
    principio_ativo: "Clonazepam",
    dosagem: "2mg",
    forma_farmaceutica: "Comprimido",
    categoria: "CONTROLADO",
    exige_receita: true,
    temperatura_controlada: false,
    estoque_disponivel: 215,
  }
];

export const MOCK_PRESCRIPTIONS: Prescription[] = [
  {
    id: "presc-1",
    paciente_id: "user-paciente-1",
    medico_nome: "Dra. Camila Vasconcelos",
    medico_crm: "189432",
    medico_uf_crm: "SP",
    data_emissao: "2026-08-20",
    data_validade: "2027-02-20",
    arquivo_receita_url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=60",
    status: "VALIDADA",
    observacoes_farmaceutico: "Receita de uso contínuo validada para 6 meses.",
    created_at: "2026-08-20T14:30:00Z",
  },
  {
    id: "presc-2",
    paciente_id: "user-paciente-1",
    medico_nome: "Dr. Roberto Martins",
    medico_crm: "142981",
    medico_uf_crm: "SP",
    data_emissao: "2026-09-10",
    data_validade: "2026-10-10",
    arquivo_receita_url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=60",
    status: "PENDENTE_VALIDACAO",
    created_at: "2026-09-14T09:15:00Z",
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-1",
    protocolo: "MOTO-2026-0915-081",
    paciente_id: "user-paciente-1",
    paciente: MOCK_CURRENT_USER,
    polo_origem_id: "polo-central-sp-sul",
    prescription_id: "presc-1",
    prescription: MOCK_PRESCRIPTIONS[0],
    status: "EM_ROTA",
    endereco_entrega_rua: "Rua das Flores",
    endereco_entrega_numero: "250",
    endereco_entrega_bairro: "Jardim das Palmeiras",
    endereco_entrega_cidade: "São Paulo",
    endereco_entrega_uf: "SP",
    endereco_entrega_cep: "04567-000",
    observacao_paciente: "Interfone 24 - Deixar com a portaria se ausente",
    data_previsao_entrega: "2026-09-15",
    items: [
      {
        id: "item-1",
        order_id: "ord-1",
        medication_id: "med-1",
        medication: MOCK_MEDICATIONS[0],
        quantidade_solicitada: 60,
        quantidade_atendida: 60,
        lote_atendido: "LT-LOS-9982",
      },
      {
        id: "item-2",
        order_id: "ord-1",
        medication_id: "med-3",
        medication: MOCK_MEDICATIONS[2],
        quantidade_solicitada: 2,
        quantidade_atendida: 2,
        lote_atendido: "LT-INS-2026",
      }
    ],
    created_at: "2026-09-15T08:30:00Z",
    updated_at: "2026-09-15T10:15:00Z",
  },
  {
    id: "ord-2",
    protocolo: "MOTO-2026-0914-042",
    paciente_id: "user-paciente-1",
    paciente: MOCK_CURRENT_USER,
    polo_origem_id: "polo-central-sp-sul",
    prescription_id: "presc-1",
    status: "APROVADO_PREPARACAO",
    endereco_entrega_rua: "Rua das Flores",
    endereco_entrega_numero: "250",
    endereco_entrega_bairro: "Jardim das Palmeiras",
    endereco_entrega_cidade: "São Paulo",
    endereco_entrega_uf: "SP",
    endereco_entrega_cep: "04567-000",
    data_previsao_entrega: "2026-09-16",
    items: [
      {
        id: "item-3",
        order_id: "ord-2",
        medication_id: "med-2",
        medication: MOCK_MEDICATIONS[1],
        quantidade_solicitada: 90,
        quantidade_atendida: 90,
        lote_atendido: "LT-MET-5411",
      }
    ],
    created_at: "2026-09-14T14:10:00Z",
    updated_at: "2026-09-15T09:00:00Z",
  },
  {
    id: "ord-3",
    protocolo: "MOTO-2026-0913-019",
    paciente_id: "user-paciente-1",
    paciente: MOCK_CURRENT_USER,
    polo_origem_id: "polo-central-sp-sul",
    prescription_id: "presc-1",
    status: "ENTREGUE",
    endereco_entrega_rua: "Rua das Flores",
    endereco_entrega_numero: "250",
    endereco_entrega_bairro: "Jardim das Palmeiras",
    endereco_entrega_cidade: "São Paulo",
    endereco_entrega_uf: "SP",
    endereco_entrega_cep: "04567-000",
    data_previsao_entrega: "2026-09-13",
    items: [
      {
        id: "item-4",
        order_id: "ord-3",
        medication_id: "med-5",
        medication: MOCK_MEDICATIONS[4],
        quantidade_solicitada: 30,
        quantidade_atendida: 30,
        lote_atendido: "LT-SIN-1102",
      }
    ],
    created_at: "2026-09-13T09:00:00Z",
    updated_at: "2026-09-13T16:45:00Z",
  }
];
